INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000001',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','lat-pulldown',NULL,'cable','{"schemaVersion":1,"angle":"unspecified","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["lats"],"secondary":["biceps"]}','active',NULL,NULL,NULL,NULL,'vertical_pull','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://contentcdn.eacefitness.com/April2018/ACE_BackExerStudy.pdf"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000001','zh-Hans','高位下拉（绳索）','高位下拉（绳索）');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000001','zh-Hant','高位下拉（滑輪）','高位下拉（滑輪）');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000001','en','Lat pulldown (cable)','Lat pulldown (cable)');
--> statement-breakpoint
INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000002',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','seated-row',NULL,'cable','{"schemaVersion":1,"angle":"unspecified","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["upper_back"],"secondary":["lats","biceps"]}','active',NULL,NULL,NULL,NULL,'horizontal_pull','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://www.acefitness.org/resources/everyone/exercise-library/48/seated-row/"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000002','zh-Hans','坐姿划船（绳索）','坐姿划船（绳索）');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000002','zh-Hant','坐姿划船（滑輪）','坐姿划船（滑輪）');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000002','en','Seated cable row','Seated cable row');
--> statement-breakpoint
INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000003',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','assisted-pull-up',NULL,'machine','{"schemaVersion":1,"angle":"unspecified","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["lats"],"secondary":["biceps"]}','active',NULL,NULL,NULL,NULL,'vertical_pull','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://www.intenzafitness.com/wp-content/uploads/2025/11/Intenza-EL12-Assisted-Chin-Dip-Owners-Manual.pdf"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000003','zh-Hans','辅助引体向上','辅助引体向上');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000003','zh-Hant','輔助引體向上','輔助引體向上');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000003','en','Assisted pull-up','Assisted pull-up');
--> statement-breakpoint
INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000004',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','barbell-bench-press',NULL,'barbell','{"schemaVersion":1,"angle":"flat","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["chest"],"secondary":["triceps","shoulders"]}','active',NULL,NULL,NULL,NULL,'horizontal_push','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://www.acefitness.org/resources/pros/expert-articles/8972/be-a-chest-day-champion-an-evidence-based-approach-to-training-the-chest/"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000004','zh-Hans','杠铃平板卧推','杠铃平板卧推');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000004','zh-Hant','槓鈴平板臥推','槓鈴平板臥推');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000004','en','Barbell bench press','Barbell bench press');
--> statement-breakpoint
INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000005',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','incline-dumbbell-press',NULL,'dumbbell','{"schemaVersion":1,"angle":"incline","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["chest"],"secondary":["shoulders","triceps"]}','active',NULL,NULL,NULL,NULL,'horizontal_push','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://www.nasm.org/resource-center/exercise-library/two-arm-incline-dumbbell-chest-press"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000005','zh-Hans','哑铃上斜卧推','哑铃上斜卧推');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000005','zh-Hant','啞鈴上斜臥推','啞鈴上斜臥推');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000005','en','Incline dumbbell press','Incline dumbbell press');
--> statement-breakpoint
INSERT INTO exercise_definitions (id,owner_id,revision,created_at,updated_at,deleted_at,scope,catalog_version,family_id,parent_exercise_id,equipment_type,variant_json,muscle_groups_json,status,personal_name,personal_locale,operation_id,created_operation_id,movement_pattern,catalog_review_json) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000006',NULL,'1','2026-09-17T20:36:00.714Z','2026-09-17T20:36:00.714Z',NULL,'system','training-2026-09-17.1','assisted-dip',NULL,'machine','{"schemaVersion":1,"angle":"unspecified","grip":"unspecified","laterality":"unspecified","note":null}','{"schemaVersion":1,"primary":["triceps","chest"],"secondary":["shoulders"]}','active',NULL,NULL,NULL,NULL,'vertical_push','{"status":"approved","reviewedBy":"product-owner","reviewedAt":"2026-09-17T20:36:00.714Z","record":"docs/catalog-training-first-six.md","sourceUrls":["https://www.intenzafitness.com/wp-content/uploads/2025/11/Intenza-EL12-Assisted-Chin-Dip-Owners-Manual.pdf"],"sourceNote":"Identity checked against the listed primary sources; project movement and muscle classifications approved by the product owner."}');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000006','zh-Hans','辅助双杠臂屈伸','辅助双杠臂屈伸');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000006','zh-Hant','輔助雙槓臂屈伸','輔助雙槓臂屈伸');
--> statement-breakpoint
INSERT INTO exercise_labels (exercise_id,locale,display_name,search_terms) VALUES ('bdeba6ce-c5ba-4a1b-9910-000000000006','en','Assisted dip','Assisted dip');
