import { workspaceLocale } from './workspace-resources.ts';
export const namespaces = ['common', 'auth', 'today', 'weight', 'training', 'nutrition', 'assistant', 'insights', 'reports', 'settings', 'errors', 'a11y'] as const;
const empty = { auth: {}, today: {}, weight: {}, training: {}, nutrition: {}, assistant: {}, insights: {}, reports: {}, settings: {} };
const baseResources = {
  'en': { ...empty,
    common: { brand: 'lowkkey', preview: 'Early preview', eyebrow: 'A little attention, every day.', title: 'Make room for\nyour progress.', description: 'Your personal space for training, meals, and the changes that matter to you.', language: 'Language', displayPreview: 'Make yourself at home', displayDescription: 'Try the display language and number format. This preview does not save health records.', value: 'Example weight', format: 'Preview number', formatted: 'Display: {{value}} kg', serviceReady: 'Preview connected', serviceUnavailable: 'Connection unavailable', foundation: 'A foundation for your daily practice', foundationBody: 'Record simply. Understand your history. Decide what comes next.', personal: 'Personal by design', personalBody: 'Your records belong in your own space.', steady: 'At your own pace', steadyBody: 'Small observations, over time.' },
    errors: { adminRequired: 'Only an administrator can do this.', invitationExpired: 'This invitation has expired. Ask the administrator to renew it.', memberLimit: 'Five active or invited members already occupy the available places.', lastAdmin: 'Keep at least one active administrator.', invalidRequest: 'Check the request and try again.', recordChanged: 'This record changed elsewhere. Review the current value before saving.', needsConfirmation: 'Check these details before saving.', idempotencyReused: 'This save request was already used for different content. Review your changes.', duplicateCandidate: 'A record with this identity already exists. Review it before creating another.', invalidInput: 'Enter a number such as 34.3, using a decimal point.', recordNotFound: 'This resource is unavailable.', temporaryFailure: 'Something went wrong. Please try again.', authRequired: 'Sign in to continue.', memberSuspended: 'This membership is not active.', unavailable: 'Unavailable' },
    a11y: { main: 'Main content', language: 'Display language', connection: 'Connection status' },
  },
  'zh-Hans': { ...empty,
    common: { brand: 'lowkkey', preview: '初始预览', eyebrow: '每天，留一点心给自己。', title: '为每一点进步，\n留出空间。', description: '属于你的日常空间，记录训练、饮食，以及值得关注的变化。', language: '语言', displayPreview: '从熟悉的表达开始', displayDescription: '试试显示语言与数字格式。此预览不会保存健康记录。', value: '示例重量', format: '预览数字', formatted: '显示：{{value}} kg', serviceReady: '预览已连接', serviceUnavailable: '暂时无法连接', foundation: '为日常积累，打好基础', foundationBody: '简单记录，读懂过去，再决定下一步。', personal: '属于自己的空间', personalBody: '你的记录，留在你自己的空间里。', steady: '按自己的节奏', steadyBody: '从一点观察开始，慢慢积累。' },
    errors: { adminRequired: '只有管理员可以执行此操作。', invitationExpired: '邀请已过期，请联系管理员续期。', memberLimit: '五个成员名额已由启用或受邀成员占用。', lastAdmin: '必须保留至少一位启用的管理员。', invalidRequest: '请检查输入后重试。', recordChanged: '这条记录已在别处修改，请核对当前值后再保存。', needsConfirmation: '请核对这些信息后再保存。', idempotencyReused: '这次保存请求已用于其他内容，请核对修改。', duplicateCandidate: '这条记录已存在，请查看后再决定是否新增。', invalidInput: '请输入如 34.3 的数字，使用小数点。', recordNotFound: '此内容暂不可用。', temporaryFailure: '暂时遇到问题，请重试。', authRequired: '请登录后继续。', memberSuspended: '当前成员资格未启用。', unavailable: '暂不可用' },
    a11y: { main: '主要内容', language: '显示语言', connection: '连接状态' },
  },
  'zh-Hant': { ...empty,
    common: { brand: 'lowkkey', preview: '初始預覽', eyebrow: '每天，留一點心給自己。', title: '為每一點進步，\n留出空間。', description: '屬於你的日常空間，記錄訓練、飲食，以及值得關注的變化。', language: '語言', displayPreview: '從熟悉的表達開始', displayDescription: '試試顯示語言與數字格式。此預覽不會儲存健康紀錄。', value: '範例重量', format: '預覽數字', formatted: '顯示：{{value}} kg', serviceReady: '預覽已連線', serviceUnavailable: '暫時無法連線', foundation: '為日常累積，打好基礎', foundationBody: '簡單記錄，讀懂過去，再決定下一步。', personal: '屬於自己的空間', personalBody: '你的紀錄，留在你自己的空間裡。', steady: '照自己的步調', steadyBody: '從一點觀察開始，慢慢累積。' },
    errors: { adminRequired: '只有管理員可以執行此操作。', invitationExpired: '邀請已過期，請聯絡管理員延長期限。', memberLimit: '五個成員名額已由啟用或受邀成員占用。', lastAdmin: '必須保留至少一位啟用的管理員。', invalidRequest: '請檢查輸入後再試一次。', recordChanged: '這筆紀錄已在別處修改，請核對目前的值後再儲存。', needsConfirmation: '請核對這些資訊後再儲存。', idempotencyReused: '這次儲存請求已用於其他內容，請核對修改。', duplicateCandidate: '這筆紀錄已存在，請查看後再決定是否新增。', invalidInput: '請輸入如 34.3 的數字，使用小數點。', recordNotFound: '此內容暫時無法使用。', temporaryFailure: '暫時遇到問題，請再試一次。', authRequired: '請登入後繼續。', memberSuspended: '目前的成員資格尚未啟用。', unavailable: '暫時無法使用' },
    a11y: { main: '主要內容', language: '顯示語言', connection: '連線狀態' },
  },
};
function withWorkspace<T extends typeof baseResources[keyof typeof baseResources]>(base: T, index: 0 | 1 | 2) {
  const extra = workspaceLocale(index);
  return { ...base, common: { ...base.common, ...extra.common }, auth: extra.auth, today: extra.today, weight: extra.weight, assistant: extra.assistant, settings: extra.settings };
}
export const resources = { en: withWorkspace(baseResources.en, 0), 'zh-Hans': withWorkspace(baseResources['zh-Hans'], 1), 'zh-Hant': withWorkspace(baseResources['zh-Hant'], 2) };
