// Each entry is independently worded: English, Simplified Chinese, Traditional Chinese.
const messages = {
  common: {
    loadFailed: ['Could not load your records. Please retry.', '暂时无法读取记录，请重试。', '暫時無法讀取紀錄，請重試。'], offlineUnavailable: ['No records are cached on this device yet. Reconnect and retry.', '此设备尚无缓存记录，请联网后重试。', '此裝置尚無快取紀錄，請連線後重試。'],
    today: ['Today', '今日', '今日'], back: ['Back', '返回', '返回'], save: ['Save', '保存', '儲存'], edit: ['Edit', '修改', '修改'], remove: ['Delete', '删除', '刪除'], cancel: ['Cancel', '取消', '取消'], retry: ['Retry', '重试', '重試'], review: ['Review', '核对', '核對'], undo: ['Undo', '撤销', '復原'], discard: ['Discard this local change', '放弃这条本机修改', '放棄這筆本機修改'],
    loading: ['Loading your records…', '正在读取你的记录…', '正在讀取你的紀錄…'], noRecords: ['Not recorded', '尚未记录', '尚未記錄'], savedLocally: ['Saved on this device · awaiting sync', '已暂存此设备，待同步', '已暫存此裝置，待同步'], synced: ['Synced', '已同步', '已同步'], syncing: ['Syncing', '正在同步', '正在同步'], syncFailed: ['Still on this device · sync failed', '暂存仍在，同步失败', '暫存仍在，同步失敗'], conflict: ['Changed elsewhere · review needed', '记录已在别处修改，需要核对', '紀錄已在別處修改，需要核對'], needsReview: ['Review before syncing', '核对后再同步', '核對後再同步'], rejected: ['Check the details before saving', '请核对信息后保存', '請核對資訊後儲存'], pendingCount: ['{{count}} changes awaiting sync', '{{count}} 条修改待同步', '{{count}} 筆修改待同步'],
    offline: ['Offline · showing records saved on this device', '当前离线，显示此设备已保存的记录', '目前離線，顯示此裝置已儲存的紀錄'], storageFailed: ['Could not save on this device. Keep this page open and try again.', '未能保存到此设备，请保留当前页面并重试。', '無法儲存至此裝置，請保留目前頁面並重試。'], savedDraft: ['Input saved on this device', '输入已暂存此设备', '輸入已暫存此裝置'],
    unit: ['Unit', '单位', '單位'], date: ['Date', '日期', '日期'], unknown: ['Not provided', '未提供', '未提供'], settings: ['Settings', '设置', '設定'], details: ['Open details', '查看详情', '查看詳情'], changeLanguage: ['Display language', '显示语言', '顯示語言'], refresh: ['Refresh records', '刷新记录', '重新整理紀錄'], unavailableFeature: ['This part of the recording interface is still being built.', '这部分记录界面还在建设中。', '這部分記錄介面仍在建置中。'],
  },
  auth: {
    title: ['Your fitness, at a glance.', '训练、体重与饮食，一目了然。', '訓練、體重與飲食，一目瞭然。'], intro: ['Record your activity. Review your progress.', '记录日常，查看变化。', '記錄日常，查看變化。'], signIn: ['Sign in', '登录', '登入'], localSignIn: ['Open local demo', '打开本地演示', '開啟本機示範'], localOnly: ['This local demo uses fictional records.', '本地演示只使用虚构记录。', '本機示範僅使用虛構紀錄。'], activate: ['Set up your profile', '设置个人档案', '設定個人檔案'], name: ['What should we call you?', '怎么称呼你？', '怎麼稱呼你？'], goal: ['Your goal', '你的目标', '你的目標'], chooseGoal: ['Choose a goal', '选择目标', '選擇目標'], lean_bulk: ['Build muscle', '增肌', '增肌'], fat_loss: ['Lose fat', '减脂', '減脂'], maintenance: ['Maintain', '维持', '維持'],
    timezone: ['Your time zone', '你所在的时区', '你所在的時區'], timezoneHelp: ['Confirm this time zone. It determines which day your records belong to.', '请确认时区，它决定记录归属哪一天。', '請確認時區，它決定紀錄歸屬哪一天。'], begin: ['Start recording', '开始记录', '開始記錄'], invitation: ['Your invitation is ready.', '你的邀请已准备好。', '你的邀請已準備好。'], memoryNotice: ['When conversation features are available, you can review, correct or turn off remembered preferences in Settings.', '对话功能开放后，你可以在设置中查看、纠正或关闭已记住的偏好。', '對話功能開放後，你可以在設定中查看、修正或關閉已記住的偏好。'],
    signedOut: ['Sign in again to continue. Your unsynced entries stay on this device.', '请重新登录后继续，未同步内容仍保留在此设备。', '請重新登入後繼續，未同步內容仍保留在此裝置。'], inactive: ['This membership is no longer active. Online access has stopped.', '当前成员资格未启用，在线访问已停止。', '目前的成員資格尚未啟用，線上存取已停止。'], signOut: ['Sign out', '退出登录', '登出'], pendingExit: ['There are unsynced records or input drafts on this device.', '此设备还有未同步的记录或输入草稿。', '此裝置還有未同步的紀錄或輸入草稿。'], exportLocal: ['Download local drafts and changes', '下载本机草稿与待同步修改', '下載本機草稿與待同步修改'], exportThenExit: ['I saved the download · sign out', '已保存下载，继续退出', '已儲存下載，繼續登出'], discardThenExit: ['Discard local drafts · sign out', '放弃本机草稿并退出', '放棄本機草稿並登出'], exitExplanation: ['Discarding local drafts does not delete records already saved on the server.', '放弃本机草稿不会删除服务器上已保存的记录。', '放棄本機草稿不會刪除伺服器上已儲存的紀錄。'], syncFirst: ['Return to syncing', '返回同步', '返回同步'], localExported: ['Check your download before signing out.', '请确认下载文件已保存，再继续退出。', '請確認下載檔案已儲存，再繼續登出。'],
  },
  today: {
    unknownEnergy: ['{{count}} items have no energy value', '{{count}} 项未提供热量', '{{count}} 項未提供熱量'], estimated: ['Includes estimates', '包含估算值', '包含估算值'],
    title: ['Today', '今日状态', '今日狀態'], hello: ['{{name}}, here is your latest activity.', '{{name}}，查看最近记录。', '{{name}}，查看最近紀錄。'], training: ['Training', '训练', '訓練'], weight: ['Weight', '体重', '體重'], nutrition: ['Meals', '饮食', '飲食'], trainingEmpty: ['No training in progress', '当前没有进行中的训练', '目前沒有進行中的訓練'], trainingContinue: ['Continue training', '继续训练', '繼續訓練'], trainingStart: ['Open training', '打开训练', '開啟訓練'], weigh: ['Record weight', '称重', '量體重'], recordMeal: ['Record a meal', '记餐', '記餐'], latestWeight: ['Latest primary weight', '最近主要体重', '最近主要體重'], loggedEnergy: ['Logged energy', '已记录摄入', '已記錄攝取量'], protein: ['Logged protein', '已记录蛋白质', '已記錄蛋白質'], incomplete: ['Includes only what you have recorded', '只包含你已经记录的内容', '只包含你已經記錄的內容'], noGoal: ['No nutrition goal set', '尚未设置营养目标', '尚未設定營養目標'],
    remainingProtein: ['About {{amount}} g to your protein target, based on your records', '按已记录内容，距离蛋白质目标约差 {{amount}} g', '依已記錄內容，距離蛋白質目標約差 {{amount}} g'], overProtein: ['{{amount}} g above your protein target in recorded intake', '已记录蛋白质比目标多 {{amount}} g', '已記錄蛋白質比目標多 {{amount}} g'], pendingMeals: ['{{count}} meals to finish reviewing', '{{count}} 餐待完善', '{{count}} 餐待完善'], unknownProtein: ['{{count}} items have no protein value', '{{count}} 项未提供蛋白质', '{{count}} 項未提供蛋白質'], unreviewed: ['Completeness not reviewed', '尚未核对完整度', '尚未核對完整度'], partial: ['Partially recorded', '部分记录', '部分記錄'], complete: ['You confirmed this day was complete', '你已确认当天基本记全', '你已確認當天大致記齊'],
  },
  weight: {
    created: ['Measurement saved and synced.', '这次测量已保存并同步。', '這次測量已儲存並同步。'], updated: ['Measurement updated and synced.', '修改已保存并同步。', '修改已儲存並同步。'], deleted: ['Measurement deleted and synced.', '这次测量已删除并同步。', '這次測量已刪除並同步。'], undone: ['The operation was undone and synced.', '操作已撤销并同步。', '操作已復原並同步。'],
    undoNew: ['Undo this new measurement', '撤销这次新增', '復原這筆新增'], undoAction: ['Undoing a weight operation', '正在撤销体重操作', '正在復原體重操作'], undoBlocked: ['This operation could not be undone. Later changes have been preserved. Review the history before taking another action.', '这次操作未能撤销，后续修改已保留。请先查看历史，再决定下一步。', '這次操作無法復原，後續修改已保留。請先查看歷史，再決定下一步。'], deleteAction: ['Deleting a measurement', '正在删除一次测量', '正在刪除一筆測量'],
    primaryPromoted: ['The earliest remaining measurement on {{date}}, {{value}} {{unit}}, is now primary.', '{{date}} 剩余记录中最早的 {{value}} {{unit}} 已成为主要记录。', '{{date}} 剩餘紀錄中最早的 {{value}} {{unit}} 已成為主要紀錄。'], primaryPromotedPending: ['The earliest remaining measurement was promoted to primary. Refreshing the history…', '已将当天剩余记录中最早的一条设为主要记录，正在刷新历史…', '已將當天剩餘紀錄中最早的一筆設為主要紀錄，正在重新整理歷史…'], deletePrimaryEffect: ['If other measurements remain on this day, the earliest one will become primary and the trend will update.', '如果当天还有其他测量，最早的一条会成为主要记录，趋势也会更新。', '若當天還有其他測量，最早的一筆會成為主要紀錄，趨勢也會更新。'],
    primaryChanged: ['The primary record changed. Choose again after reviewing it.', '主要记录已变化，请核对后重新选择。', '主要紀錄已變更，請核對後重新選擇。'], chartDescription: ['Solid dots: primary measurements. Hollow dots: additional measurements. Line: 7-day average.', '实心点为主要测量，空心点为额外测量，曲线为 7 日均值。', '實心點為主要測量，空心點為額外測量，曲線為 7 日均值。'],
    title: ['Weight', '体重', '體重'], subtitle: ['Record a measurement. Review your history and trend.', '记录体重，查看历史与趋势。', '記錄體重，查看歷史與趨勢。'], new: ['Record weight', '记一次体重', '記一次體重'], value: ['Weight', '体重', '體重'], condition: ['Measurement conditions', '测量状态', '測量狀態'], unspecified: ['Not specified', '未指定', '未指定'], fasted: ['Fasted', '空腹', '空腹'], other: ['Other', '其他', '其他'], sameDay: ['Another primary weight exists for this day.', '当天已有一条主要体重。', '當天已有一筆主要體重。'], primaryChoice: ['Use this measurement as', '将这次测量保留为', '將這次測量保留為'], extra: ['An additional record', '额外记录', '額外紀錄'], replace: ['The primary record for this day', '当天主要记录', '當天主要紀錄'],
    outlier: ['This differs by more than 5% from {{value}} {{unit}} on {{date}}. Check the value and unit.', '这次比 {{date}} 的 {{value}} {{unit}} 变化超过 5%，请核对数值和单位。', '這次比 {{date}} 的 {{value}} {{unit}} 變化超過 5%，請核對數值和單位。'], confirmOutlier: ['I checked the weight and unit', '已核对体重和单位', '已核對體重和單位'], primary: ['Primary', '主要记录', '主要紀錄'], additional: ['Additional', '额外记录', '額外紀錄'], original: ['Original: {{value}} {{unit}}', '原始记录：{{value}} {{unit}}', '原始紀錄：{{value}} {{unit}}'], trend: ['7-day trend', '7 日趋势', '7 日趨勢'], insufficient: ['At least 3 measured days in a 7-day window are needed for a trend.', '7 日窗口内至少有 3 个实际测量日，才会显示趋势。', '7 日區間內至少有 3 個實際測量日，才會顯示趨勢。'], samples: ['{{count}} measured days in the latest window', '最近窗口有 {{count}} 个测量日', '最近區間有 {{count}} 個測量日'],
    history: ['Measurements', '称重记录', '體重紀錄'], noHistory: ['No measurements yet. Record your first weight above.', '暂无称重记录，在上方记录第一次体重。', '尚無體重紀錄，請在上方記錄第一次體重。'], editTitle: ['Review this measurement', '核对这次测量', '核對這次測量'], editingBaseline: ['You are editing the version you opened. Later changes will need review.', '正在修改打开时的版本；后续变化会提示你核对。', '正在修改開啟時的版本；後續變更會提示你核對。'], deleteConfirm: ['Delete {{value}} {{unit}} on {{date}}? Trends will update. If this is the primary record, the earliest remaining measurement becomes primary.', '删除 {{date}} 的 {{value}} {{unit}}？趋势会更新；若是主要记录，将由当天最早的剩余测量接替。', '刪除 {{date}} 的 {{value}} {{unit}}？趨勢會更新；若是主要紀錄，將由當天最早的剩餘測量接替。'], pending: ['Changes on this device', '此设备上的修改', '此裝置上的修改'], candidate: ['Your entered value: {{value}} {{unit}}', '你的输入：{{value}} {{unit}}', '你的輸入：{{value}} {{unit}}'], current: ['Currently saved: {{value}} {{unit}}', '当前已保存：{{value}} {{unit}}', '目前已儲存：{{value}} {{unit}}'], missingTarget: ['The original record is no longer available. You can keep this draft or discard it.', '原记录已不可用，你可以保留草稿或明确放弃。', '原紀錄已無法使用，你可以保留草稿或明確放棄。'], loadMore: ['Show more measurements', '查看更多测量', '查看更多測量'], useCurrent: ['Review my value against the current record', '对照当前记录核对我的输入', '對照目前紀錄核對我的輸入'], saveSuccess: ['Your measurement is saved on this device and ready to sync.', '这次测量已暂存此设备，准备同步。', '這次測量已暫存此裝置，準備同步。'], dateOnly: ['Time not provided', '未提供时间', '未提供時間'], confirmDelete: ['Delete measurement', '删除这次测量', '刪除這次測量'],
  },
  assistant: {
    open: ['Chat', '对话', '對話'], openLabel: ['Open conversation', '打开对话', '開啟對話'], back: ['Back to records', '返回记录', '返回紀錄'], title: ['Conversation', '对话', '對話'], unavailable: ['Conversation is not connected yet. You can keep a note here and return to your records.', '对话暂未接通。你可以先在这里留段文字，再返回记录。', '對話尚未連線。你可以先在這裡留段文字，再返回紀錄。'], draft: ['Unsent note', '未发送的文字', '未傳送的文字'], offline: ['Notes stay on this device. Reconnecting will not send them automatically.', '文字只暂存此设备，恢复联网不会自动发送。', '文字僅暫存此裝置，恢復連線不會自動傳送。'],
  },
  settings: { title: ['Your preferences', '你的偏好', '你的偏好'], units: ['Weight display unit', '体重显示单位', '體重顯示單位'], pending: ['This preference is saved locally until the server confirms it.', '此偏好先保存在本机，收到服务器回执后才算同步。', '此偏好先儲存在本機，收到伺服器回覆後才算同步。'], exportTitle: ['Your local data', '你的本机资料', '你的本機資料'], logoutTitle: ['Account access', '账户访问', '帳戶存取'], profile: ['Profile', '个人档案', '個人檔案'] },
} satisfies Record<string, Record<string, [string, string, string]>>;

export function workspaceLocale(index: 0 | 1 | 2): Record<string, Record<string, string>> {
  return Object.fromEntries(Object.entries(messages).map(([namespace, entries]) => [namespace, Object.fromEntries(Object.entries(entries).map(([key, values]) => [key, values[index]]))]));
}
