import {test,expect} from '@playwright/test';

test('isolated rehearsal uses real MCP proposals, one batch confirmation, live charts and append-only undo',async({page},info)=>{
  test.setTimeout(60000);
  await page.goto('http://127.0.0.1:5180/');
  await page.getByRole('button',{name:'重置演练',exact:true}).click();
  await expect(page.locator('#status')).toContainText('已重置', {timeout:20000});
  const app=page.frameLocator('iframe'),login=app.getByRole('button',{name:'进入状态舱'});
  await app.locator('.screen,.access-gate button').first().waitFor();if(await login.isVisible())await login.click();
  const main=app.locator('[data-screen="Main"]');await expect(main).toContainText('杠铃平板卧推、坐姿绳索划船');
  const frame=page.frames().find(frame=>frame.url().includes(':5181/'))!;
  const state=()=>frame.evaluate(async()=>await(await fetch('/v1/state')).json());
  const initial=await state();expect(initial.entries).toHaveLength(5);
  await main.screenshot({animations:'disabled',path:`.artifacts/playwright/${info.project.name}/rehearsal-main.png`});
  await page.getByRole('button',{name:'模拟 AI 提交计划调整',exact:true}).click();await expect(page.locator('#status')).toContainText('尚未生效');
  const pending=await state();expect(pending.program).toEqual(initial.program);expect(pending.proposals).toHaveLength(1);expect(pending.proposals[0].author.actor).toBe('model');
  await page.getByRole('button',{name:'模拟 AI 提交计划调整',exact:true}).click();await expect(page.locator('#status')).toContainText('尚未生效');expect((await state()).proposals).toHaveLength(1);
  await main.getByRole('button',{name:'查看并确认',exact:true}).click();const sheet=app.getByRole('dialog',{name:'查看建议'});
  await expect(sheet).toContainText('AI 已提交');await expect(sheet).toContainText('当前');await expect(sheet).toContainText('采用后');
  await sheet.screenshot({animations:'disabled',path:`.artifacts/playwright/${info.project.name}/rehearsal-review.png`});
  await sheet.getByRole('button',{name:'采用',exact:true}).click();await expect(sheet).toHaveCount(0);
  await expect.poll(async()=>(await state()).program.days[0].items[1].sets).toBe(3);
  await page.getByRole('button',{name:'模拟 AI 提交 5 条记录',exact:true}).click();await expect(page.locator('#status')).toContainText('尚未入账');
  expect((await state()).entries).toHaveLength(5);
  await main.getByRole('button',{name:'查看并确认',exact:true}).click();const review=app.getByRole('dialog',{name:'确认'});
  await expect(review).toContainText('待写入 5 项');await expect(review).toContainText('演练客户端（非真实 AI）');
  await review.locator('[data-action="submission-accept"]').click();await expect(review).toHaveCount(0);
  const confirmed=await state();expect(confirmed.entries).toHaveLength(10);expect(confirmed.entries.filter((entry:{source:{actor:string}})=>entry.source.actor==='model')).toHaveLength(5);
  await page.getByRole('button',{name:'模拟 AI 提交 5 条记录',exact:true}).click();await expect(page.locator('#status')).toContainText('重复点击不会重复提交');expect((await state()).entries).toHaveLength(10);
  await app.getByRole('link',{name:'体征',exact:true}).click();await expect(app.locator('[data-bind="body-chart"]')).toHaveAttribute('aria-label','2 次真实称重');
  await app.getByRole('link',{name:'进步',exact:true}).click();await expect(app.locator('[data-bind="progress-chart"] g')).toHaveCount(4);
  await app.locator('[data-screen="Progress"]').screenshot({animations:'disabled',path:`.artifacts/playwright/${info.project.name}/rehearsal-progress.png`});
  await app.getByRole('link',{name:'日志',exact:true}).click();
  const modelWeight=confirmed.entries.find((entry:{kind:string;source:{actor:string}})=>entry.kind==='weight'&&entry.source.actor==='model');
  const row=app.locator(`[data-entry-id="${modelWeight.id}"]`);await row.getByRole('button',{name:'撤销',exact:true}).click();await expect(row).toContainText('已撤销');
  const undone=await state();expect(undone.entries).toHaveLength(11);expect(undone.entries.some((entry:{kind:string;targetId?:string})=>entry.kind==='revert'&&entry.targetId===modelWeight.id)).toBe(true);
  await app.getByRole('link',{name:'体征',exact:true}).click();await expect(app.locator('[data-bind="body-chart"]')).toHaveAttribute('aria-label','1 次真实称重');
  await app.getByRole('link',{name:'接入',exact:true}).click();await expect(app.locator('[data-screen="Connect"]')).toContainText('演练客户端（非真实 AI）');await expect(app.locator('[data-screen="Connect"]')).not.toContainText('MCP');
  await app.getByRole('button',{name:'撤销 演练客户端（非真实 AI） 的授权'}).click();await expect(app.locator('[data-screen="Connect"]')).toContainText('已撤销');
  await page.getByRole('button',{name:'模拟 AI 提交计划调整',exact:true}).click();await expect(page.locator('#status')).toContainText('401');
  // No public API or cross-origin site can invoke this developer-only harness.
  const denied=await page.request.post('http://127.0.0.1:5180/action/reset',{headers:{Origin:'https://example.com'}});expect(denied.status()).toBe(403);
});
