import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { rehearsalClient } from '../scripts/rehearsal/client.mjs';
const origin = process.env.LOWKKEY_TEST_ORIGIN ?? 'http://127.0.0.1:5174';
const client = await rehearsalClient(Number(new URL(origin).port));
const tools = await client.rpc('tools/list',{});
assert.deepEqual(tools.tools.map(t=>t.name).sort(),['get_brief','log_session','log_weight','set_plan']);
const contract = JSON.parse(await readFile('docs/lowkkey-handoff/protocol/mcp-tools.json','utf8'));
for (const declared of contract.tools) {
  const actual = tools.tools.find(t=>t.name===declared.name);
  assert.deepEqual(actual.inputSchema.properties,declared.inputSchema.properties,declared.name+' input');
  assert.deepEqual(actual.outputSchema.properties,declared.outputSchema.properties,declared.name+' output');
  assert.deepEqual(actual.annotations,declared.annotations);
  assert.deepEqual(actual.securitySchemes,[{type:'oauth2',scopes:[declared.name==='get_brief'?'read':'write']}]);
}
const before = await client.tool('get_brief',{});
assert.equal(before.sessions.length,0);
const first = await client.tool('log_weight',{date:'2026-10-01',lb:160});
assert.deepEqual(await client.tool('log_weight',{date:'2026-10-01',lb:160}),first);
await client.tool('log_weight',{date:'2026-10-01',lb:162});
await client.tool('log_weight',{date:'2026-10-07',lb:164});
await client.tool('log_session',{date:'2026-10-07',raw_text:'Original\n  bench 100 × 6',sets:[{exerciseId:'bench_press',load:100,unit:'lb',loadKind:'external',reps:6}]});
await client.tool('set_plan',{day:'Chest',items:[],notes:{body:'feeling rested'}});
const brief = await client.tool('get_brief',{});
assert.equal(brief.weight_mean_7d.lb,163); assert.equal(brief.strength[0].latest.lb,120);
assert.equal(brief.sessions[0].raw_text,'Original\n  bench 100 × 6'); assert.equal(brief.body_notes,'feeling rested');
const receipt=await client.rpc('tools/call',{name:'log_session',arguments:{date:'2026-10-07',raw_text:'Original\n  bench 100 × 6',sets:[{exerciseId:'bench_press',load:100,unit:'lb',loadKind:'external',reps:6}]}});
assert.equal(receipt.structuredContent.view_url,origin+'/#Gallery?date=2026-10-07');
assert.deepEqual(JSON.parse(receipt.content[0].text),receipt.structuredContent);
assert.equal(brief.coverage.training.total_dates,1); assert.ok(brief.generated_at);
const invalid = await client.rpc('tools/call',{name:'log_weight',arguments:{date:'2026-02-30',lb:160}});
assert.equal(invalid.isError,true);
const readonly = await rehearsalClient(Number(new URL(origin).port),['read']);
assert.deepEqual((await readonly.rpc('tools/list',{})).tools.map(t=>t.name),['get_brief']);
const deniedWrite = await readonly.rpc('tools/call',{name:'log_weight',arguments:{date:'2026-10-07',lb:999}});
assert.equal(deniedWrite.isError,true);
assert.equal((await client.tool('get_brief',{})).latest_weight.lb,164);
for (const path of ['/v1/capture','/v1/entries','/v1/submissions/x/decision']) {
  const response = await fetch(origin+path,{method:'POST',headers:{Authorization:client.headers.Authorization,'Content-Type':'application/json'},body:'{}'});
  assert.equal(response.status,401);
}
const resources = await client.raw('resources/list',{});
const resourceReply = await resources.json();
assert.ok(resourceReply.error || !resourceReply.result?.resources?.length, 'no review resource');
const clients = await client.user('/v1/clients',undefined,'GET');
for (const record of clients) await client.user('/v1/clients/'+record.id+'/revoke',{});
assert.equal((await client.raw('tools/list',{})).status,401);
const refresh = await fetch(origin+'/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:client.registered.client_id,refresh_token:client.token.refresh_token,resource:origin+'/mcp'})});
assert.equal(refresh.ok,false);
console.log('Four-tool OAuth/MCP end-to-end passed');
