import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { seedShowroom,fixtureToday,fixtureWeek,fixtureSessions } from '../scripts/rehearsal/fixtures.mjs';
import { rehearsalClient } from '../scripts/rehearsal/client.mjs';
const origin = process.env.LOWKKEY_TEST_ORIGIN ?? 'http://127.0.0.1:5174';
const client = await rehearsalClient(Number(new URL(origin).port));
const tools = await client.rpc('tools/list',{});
assert.deepEqual(tools.tools.map(t=>t.name).sort(),['curate','delete','get_brief','log_session','log_weight','set_plan','set_profile']);
const contract = JSON.parse(await readFile('docs/lowkkey-handoff/protocol/mcp-tools.json','utf8'));
for (const declared of contract.tools) {
  const actual = tools.tools.find(t=>t.name===declared.name);
  assert.deepEqual(actual.inputSchema.properties,declared.inputSchema.properties,declared.name+' input');
  assert.deepEqual(actual.outputSchema.properties,declared.outputSchema.properties,declared.name+' output');
  assert.deepEqual(actual.annotations,declared.annotations);
  assert.deepEqual(actual.securitySchemes,[{type:'oauth2',scopes:[declared.name==='get_brief'?'read':'write']}]);
}
const before = await client.tool('get_brief',{});
assert.equal(before.sessions.length,0);
const first = await client.tool('log_weight',{date:fixtureToday,lb:160});
assert.deepEqual(await client.tool('log_weight',{date:fixtureToday,lb:160}),first);
await seedShowroom(client.tool);
const brief = await client.tool('get_brief',{});
assert.equal(brief.weight.mean7.n,7); assert.equal(brief.sessions.length,6);
assert.equal(brief.curation.current.week,fixtureWeek); assert.ok(brief.generated_at);
const receipt=await client.rpc('tools/call',{name:'log_session',arguments:fixtureSessions.at(-1)});
assert.equal(receipt.structuredContent.view_url,origin+'/#log?date='+fixtureToday);
assert.deepEqual(JSON.parse(receipt.content[0].text),receipt.structuredContent);
assert.equal((await client.tool('get_brief',{sessions:0})).sessions.length,0);
await client.tool('set_profile',{body_notes:null});
assert.equal((await client.tool('get_brief',{})).profile.body_notes,null);
await client.tool('curate',{week:fixtureWeek,recap:{title:'更新后的标题'}});
assert.equal((await client.tool('get_brief',{})).curation.current.recap.letter.length,2);
const removed = await client.tool('delete',{kind:'session',date:fixtureToday});
assert.equal(removed.deleted.date,fixtureToday);
assert.equal((await client.rpc('tools/call',{name:'delete',arguments:{kind:'session',date:fixtureToday}})).isError,true);
const forbidden = await client.rpc('tools/call',{name:'log_session',arguments:{...fixtureSessions[0],raw_text:'old'}});
assert.equal(forbidden.isError,true);assert.equal(forbidden.structuredContent.result.error.code,'invalid_arguments');assert.ok(forbidden.structuredContent.result.error.fields.length);
const invalid = await client.rpc('tools/call',{name:'log_weight',arguments:{date:'2026-02-30',lb:160}});
assert.equal(invalid.isError,true);
const readonly = await rehearsalClient(Number(new URL(origin).port),['read']);
assert.deepEqual((await readonly.rpc('tools/list',{})).tools.map(t=>t.name),['get_brief']);
const deniedWrite = await readonly.rpc('tools/call',{name:'log_weight',arguments:{date:'2026-10-07',lb:999}});
assert.equal(deniedWrite.isError,true);
assert.equal((await client.tool('get_brief',{})).weight.latest.lb,brief.weight.latest.lb);
for (const path of ['/v1/capture','/v1/entries','/v1/submissions/x/decision']) {
  const response = await fetch(origin+path,{method:'POST',headers:{Authorization:client.headers.Authorization,'Content-Type':'application/json'},body:'{}'});
  assert.equal(response.status,401);
}
const resources = await client.raw('resources/list',{});
const resourceReply = await resources.json();
assert.ok(resourceReply.error || !resourceReply.result?.resources?.length, 'no review resource');
const clients = await client.user('/v1/clients',undefined,'GET');
for (const record of clients) await client.user('/v1/clients/'+record.id+'/revoke',{});
assert.equal((await client.raw('tools/list',{})).status,401);
const refresh = await fetch(origin+'/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:client.registered.client_id,refresh_token:client.token.refresh_token,resource:origin+'/mcp'})});
assert.equal(refresh.ok,false);
console.log('Seven-tool OAuth/MCP end-to-end passed');
