import { useId, useLayoutEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import type { TrainingSet, Weight } from '@lowkkey/protocol';
import { plates, scoreSet, strictReps, fmt } from '@lowkkey/core';
export function useWidth(){const ref=useRef<HTMLDivElement>(null),[width,setWidth]=useState(0);useLayoutEffect(()=>{const el=ref.current!;const measure=()=>setWidth(el.clientWidth);measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect();},[]);return {ref,width};}
export function Gradient({id,width}:{id:string;width:number}){return <defs><linearGradient id={id} gradientUnits="userSpaceOnUse" x1="0" y1="0" x2={width} y2="0"><stop offset="0" style={{stopColor:'var(--g0)'}}/><stop offset=".55" style={{stopColor:'var(--g1)'}}/><stop offset="1" style={{stopColor:'var(--g2)'}}/></linearGradient></defs>;}
export const Chev=()=> <svg className="chev" viewBox="0 0 16 16" aria-hidden="true"><path d="M6 3.5 10.5 8 6 12.5"/></svg>;
const plateSizes:Record<number,[number,number,number]>={45:[450,41,1],35:[360,36,.85],25:[290,32,.7],10:[226,25,.55],5:[200,22,.45],2.5:[160,18,.35]};
export function Barbell({width,lb}:{width:number;lb:number}){const s=width/2200,H=Math.ceil(450*s)+2,cy=H/2,ps=plates(lb);let xl=415,xr=1785;const disks:ReactNode[]=[];for(const [i,p] of (ps??[]).entries()){const [d,t,o]=plateSizes[p];xl-=t;disks.push(<g key={i} className="gp" fillOpacity={o}><rect x={xl*s} y={cy-d/2*s} width={t*s} height={d*s} rx={Math.min(1.5,t*s/3)}/><rect x={xr*s} y={cy-d/2*s} width={t*s} height={d*s} rx={Math.min(1.5,t*s/3)}/></g>);xl-=5;xr+=t+5;}
return <svg width={width} height={H} viewBox={`0 0 ${width} ${H}`} role="img" aria-label={`杠铃 ${fmt(lb)} lb${ps?',每边 '+(ps.join(' + ')||'空杆'):''}`}><line x1="0" y1={cy} x2={width} y2={cy} className="gcl"/><rect x={445*s} y={cy-14*s} width={1310*s} height={28*s} className="gk"/>{[0,1785].map(x=><rect key={x} x={x*s+.5} y={cy-25*s} width={Math.max(0,415*s-1)} height={50*s} className="gs"/>)}{[415,1755].map(x=><rect key={x} x={x*s} y={cy-35*s} width={30*s} height={70*s} className="gk"/>)}{disks}</svg>;}
export function Dumbbell({width,lb}:{width:number;lb:number}){const s=width/520,hl=40+lb*1.6,hh=70+lb*1.3,hd=130,hdi=33,H=Math.ceil(hh*s)+2,cy=H/2,a=(520-(2*hl+hd))/2*s,w=hl*s,h=hh*s;const head=(x:number)=>{const c=Math.min(w,h)*.16,y=cy-h/2;return `M${x+c} ${y}H${x+w-c}L${x+w} ${y+c}V${y+h-c}L${x+w-c} ${y+h}H${x+c}L${x} ${y+h-c}V${y+c}Z`;};return <svg width={width} height={H} viewBox={`0 0 ${width} ${H}`} role="img" aria-label={`哑铃 单只 ${fmt(lb)} lb`}><line x1="0" y1={cy} x2={width} y2={cy} className="gcl"/><path d={head(a)} className="gp"/><rect x={a+w} y={cy-hdi*s/2} width={hd*s} height={hdi*s} className="gk"/><path d={head(a+w+hd*s)} className="gp"/></svg>;}
export function AssistBar({width,share}:{width:number;share:number}){const id=useId(),x=width*Math.max(0,Math.min(1,share));return <svg width={width} height="34" viewBox={`0 0 ${width} 34`} role="img" aria-label={`自己拉起 ${Math.floor(share*100)}% 体重`}><defs><pattern id={id} width="4" height="4" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line className="hatch-l" x1="0" y1="0" x2="0" y2="4"/></pattern></defs><rect x="0" y="4" width={x} height="10" className="gp" rx="2"/><rect x={x} y="4" width={Math.max(0,width-x)} height="10" fill={`url(#${id})`}/><rect x={x+.5} y="4.5" width={Math.max(0,width-x-1)} height="9" className="gf" rx="2"/>{[.25,.5,.75].map(t=><line key={t} x1={t*width} x2={t*width} y1="17" y2="20" className="gl"/>)}<text x="0" y="34">自己拉起 {Math.floor(share*100)}%</text><text x={width} y="34" textAnchor="end">徒手</text></svg>;}
export function Equipment({kind,lb=0,share}:{kind:'barbell'|'dumbbell'|'assist';lb?:number;share?:number|null}){const {ref,width}=useWidth();return <div ref={ref} className="equipment">{width>0&&(kind==='barbell'?<Barbell width={width} lb={lb}/>:kind==='dumbbell'?<Dumbbell width={Math.min(width,104)} lb={lb}/>:share!=null?<AssistBar width={width} share={share}/>:null)}</div>;}
export function Glyph({sets,date,weights}:{sets:TrainingSet[];date:string;weights:Weight[]}){let bi=-1,bv=0;sets.forEach((s,i)=>{const v=scoreSet(s,weights,date);if(v!=null&&v>bv){bv=v;bi=i;}});const max=Math.max(...sets.filter(s=>s.role!=='warmup').map(s=>s.load),1),H=22,hh=(r:number)=>3+Math.min(r,20)/20*18;let x=0;const bars=sets.map((s,i)=>{if(i&&s.role!=='warmup'&&sets[i-1].load!==s.load)x+=3;const left=x,r=strictReps(s),h=hh(r),y=H-h;x+=7;return <g key={i}>{s.role==='warmup'||s.partial?<rect x={left+.5} y={y+.5} width="3" height={Math.max(0,h-1)} className={s.role==='warmup'?'g-wu':'g-pa'}/>:<><rect x={left} y={y} width="4" height={h} rx="1" className={i===bi?'gp':'gk'} fillOpacity={i===bi?1:s.kind==='assist'?.85:.25+.6*s.load/max}/>{!!s.cheat&&<rect x={left} y={y-(hh(r+s.cheat)-h)} width="4" height={hh(r+s.cheat)-h} className="g-ch"/>}</>}</g>;});return <span className="glyph"><svg width={Math.max(0,x-3)} height={H} viewBox={`0 0 ${Math.max(1,x-3)} ${H}`} aria-hidden="true">{bars}</svg></span>;}
